{
 "title": "SpeedTest_Exporter Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "query": "5m" },
   { "name": "service_name", "query": "SpeedTest_Exporter" }
  ]
 },
 "panels": [
  {
   "title": "CPU time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$service_name\"}[5m])",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$service_name\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request count $interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=\"$service_name\"}[$interval])",
     "legendFormat": "{{handler}} {{status}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(http_request_duration_seconds_sum{job=\"$service_name\"} / http_request_duration_seconds_count{job=\"$service_name\"}) \n",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "filters": [
      { "id": "65b5c2da", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"$service_name\" && name=~\" /*\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "TraceRoute duration",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "filters": [
      { "id": "65b5c2da", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [ "PrometheusMetrics" ]
      },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"$service_name\" && name=\"TraceRoute.run\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Ping duration",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "filters": [
      { "id": "65b5c2da", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "Omada_Exporter" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [ "Prometheus.*" ],
       "valueType": "string"
      },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"$service_name\" && name=\"Ping.run\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "SpeedTest by Ookla duration",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "filters": [
      { "id": "65b5c2da", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "Omada_Exporter" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=~",
       "scope": "span",
       "tag": "name",
       "value": [ "Prometheus.*" ],
       "valueType": "string"
      },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"$service_name\" && name=\"SpeedTest.perform_speed_test\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 21, "w": 10, "x": 0, "y": 22 },
   "targets": [
    {
     "filters": [
      { "id": "26d815b2", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"$service_name\"}",
     "spss": 50,
     "tableType": "traces"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 21, "w": 14, "x": 10, "y": 22 },
   "targets": [
    {
     "expr": "{service_name=\"$service_name\"} | json message=\"message\", function=\"function\", module=\"module\", level=\"level\""
    }
   ]
  }
 ]
}