services:
  Grafana:
      image: horna-home-lab/grafana
      build:
        context: ./Grafana
        dockerfile: Dockerfile
      container_name: ${GRAFANA_CONTAINER_NAME}
      hostname: ${GRAFANA_HOSTNAME}
      restart: unless-stopped
      environment:
        TZ: ${SYSTEM_TIME_ZONE}
        GF_DATE_FORMATS_DEFAULT_TIMEZONE: ${SYSTEM_TIME_ZONE}
      volumes:
        - ./Grafana/datasources:/etc/grafana/provisioning/datasources
        - ./Grafana/dashboards_provisioning:/etc/grafana/provisioning/dashboards
        - ./Grafana/dashboards:/var/lib/grafana/dashboards
        - ./Grafana/conf:/usr/share/grafana/conf
        - GF-data:/var/lib/grafana
      command:
        - --config=/usr/share/grafana/conf/custom.ini
      ports:
        - ${GRAFANA_EXTERNAL_PORT}:3000
      healthcheck:
        test: curl --fail http://${GRAFANA_HOSTNAME}:3000/api/health
        start_period: 2s
        interval: 3s
        timeout: 1s
        retries: 5
      
  Postgres:
      image: horna-home-lab/postgres
      build:
        context: ./PostgreSQL
        dockerfile: Dockerfile
      container_name: ${POSTGRES_CONTAINER_NAME}
      hostname: ${POSTGRES_HOSTNAME}
      restart: unless-stopped
      environment:
        TZ: ${SYSTEM_TIME_ZONE}
      ports:
        - ${POSTGRES_EXTERNAL_PORT}:5432
      volumes:
        - PG-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U Actions"]
        start_period: 5s
        interval: 10s
        timeout: 5s
        retries: 10

volumes:
  GF-data:

  PG-data:
      