{
 "title": "Docker Containers",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"Docker_Containers\"},instance)"
    }
   },
   {
    "name": "include_containers",
    "label": "include_containers",
    "query": {
     "query": "label_values({job=\"Docker_Containers\"},name)"
    }
   },
   {
    "name": "exclude_containers",
    "label": "exclude_containers",
    "query": {
     "query": "label_values({job=\"Docker_Containers\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$instance\",name=~\".+\", name!~\"$exclude_containers\", name=~\"$include_containers\"}[1m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$instance\",name=~\".+\",  name!~\"$exclude_containers\", name=~\"$include_containers\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{instance=~\"$instance\",name=~\".+\", name!~\"$exclude_containers\", name=~\"$include_containers\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{instance=~\"$instance\",name=~\".+\", name!~\"$exclude_containers\", name=~\"$include_containers\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{instance=~\"$instance\",name=~\".+\", name!~\"$exclude_containers\", name=~\"$include_containers\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$instance\",name=~\".+\", name!~\"$exclude_containers\", name=~\"$include_containers\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$instance\",name=~\".+\", name!~\"$exclude_containers\", name=~\"$include_containers\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "count by(name) (count_over_time(container_last_seen{instance=~\"$instance\",name=~\".+\", name!~\"$exclude_containers\", name=~\"$include_containers\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}