{
 "title": "Internet Speed",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Controls", "type": "speakyourcode-button-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Completion status",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT get_action_completion_status(get_action_id('SpeedTest'));"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "packet_loss", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_no_workload_latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jitter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_no_workload_jitter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "download_bandwidth / 1000000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upload_bandwidth / 1000000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Packet loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "packet_loss{job=\"SpeedTest\"} * 100",
     "legendFormat": "Packet loss"
    }
   ]
  },
  {
   "title": "Internet Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    { "expr": "download_bandwidth / 1000000", "legendFormat": "Download" },
    { "expr": "upload_bandwidth / 1000000", "legendFormat": "Upload" }
   ]
  },
  {
   "title": "Transfer Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "download_latency_high", "legendFormat": "Download Latency" },
    { "expr": "upload_latency_high", "legendFormat": "Upload Latency" }
   ]
  }
 ]
}