{
 "title": "Internet Speed",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Packet Loss",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "packet_loss", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_no_workload_latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jitter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_no_workload_jitter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "download_bandwidth / 1000000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upload_bandwidth / 1000000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Internet Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    { "expr": "download_bandwidth / 1000000", "legendFormat": "Download" },
    { "expr": "upload_bandwidth / 1000000", "legendFormat": "Upload" }
   ]
  },
  {
   "title": "Transfer Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "download_latency_high", "legendFormat": "Download Latency" },
    { "expr": "upload_latency_high", "legendFormat": "Upload Latency" }
   ]
  }
 ]
}