{
 "title": "Servers Load",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Temperature Celsius",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ohm_cpu_celsius{job=\"Server-Core\", sensor=\"CPU Package\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "ohm_cpu_celsius{job=\"Ryzen9\", sensor=\"CCDs Average (Tdie)\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Load %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{job=\"Server-Core\", sensor=\"CPU Total\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "ohm_cpu_load_percent{job=\"Ryzen9\", sensor=\"CPU Total\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RAM Usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ohm_ram_load_percent{sensor=\"Memory\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "System Drive Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ohm_hdd_load_percent{job=\"Server-Core\", sensor=\"Total Activity\", hardware=\"SSDPR-CX400-01T-G2\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "ohm_hdd_load_percent{job=\"Ryzen9\", sensor=\"Total Activity\", hardware=\"Lexar SSD NM710 1TB\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network Load %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "ohm_nic_load_percent{job=\"Server-Core\", hardware=\"Hyper-V Switch\"}",
     "legendFormat": "{{job}} LACP"
    },
    {
     "expr": "ohm_nic_load_percent{job=\"Ryzen9\", hardware=\"vEthernet (Switch)\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}