apiVersion: 1

datasources:
  - name: Loki_Tempo
    type: loki
    access: proxy
    uid: ddzk98lamkwlcf
    url: http://${T_LOKI_HOSTNAME}.horna.local:{$T_LOKI_PORT}
    jsonData:
      maxLines: 100
      derivedFields:

        - matcherRegex: service_name
          matcherType: label
          name: service

        - datasourceUid: bdzfk1jvx3cowe
          matcherRegex: '"trace_id"\s*:\s*"([a-f0-9]{32})"'
          name: trace_id
          url: '$${__value.raw}'
          
        - datasourceUid: bdzfk1jvx3cowe
          matcherRegex: '"span_id"\s*:\s*"([a-f0-9]{16})"'
          name: span_id
          url: '{resource.service.name="$$service" &&  span:id = "$$span_id"}'