apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: bdzfk1jvx3cowe
    access: proxy
    url: http://apps.horna.local:3200
    isDefault: false
    version: 1
    editable: false
    basicAuth: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: ddzk98lamkwlcf
        spanStartTimeShift: '-5s'
        spanEndTimeShift: '5s'
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: adzk9jmof241se
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
      serviceMap:
        datasourceUid: adzk9jmof241se
      nodeGraph:
        enabled: true