{
 "title": "Go App Basic performance",
 "tags": [ "Go-Lang" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(go_goroutines,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_goroutines{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "process CPU time per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory reserved",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "go_threads{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC duration (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[5m]) / rate(go_gc_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m])\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}