{
 "title": "LianLi",
 "tags": [ "PC" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ohm_ram_bytes{device_name=\"LianLi\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "RAM uage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_ram_bytes{device_name=\"LianLi\",sensor=\"Memory Used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gpu temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "ohm_gpuati_celsius{device_name=\"LianLi\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Gpu temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_gpuati_celsius{device_name=\"LianLi\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Gpu wattage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_gpuati_watts{device_name=\"LianLi\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Cpu temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "ohm_cpu_celsius{device_name=\"LianLi\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Cpu Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_celsius{device_name=\"LianLi\",sensor=\"Core (Tctl/Tdie)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu wattage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_watts{device_name=\"LianLi\",sensor=\"Package\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{device_name=\"LianLi\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Ethernet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ohm_nic_bytes_per_second{device_name=\"LianLi\", hardware=\"Ethernet\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}