{
 "title": "Prometheus Targets",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prometheus Targets status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "scrape_duration_seconds{}", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "Scraped samples",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "scrape_samples_scraped", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "Added Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    { "expr": "scrape_series_added", "legendFormat": "{{job}} - {{instance}}" }
   ]
  }
 ]
}