{
 "title": "Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(prometheus_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ready",
   "type": "stat",
   "description": "Whether Prometheus startup was fully completed and the server is ready for normal operation.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_ready{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Configuration Reload",
   "type": "stat",
   "description": "Whether the last configuration reload attempt was successful.",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "stat",
   "description": "Number of scrape pool targets.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrape_pool_targets{instance=\"$instance\"})",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "stat",
   "description": "Total user and system CPU time.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "Resident memory size.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Local Storage",
   "type": "stat",
   "description": "The number of bytes that are currently used for local storage by all blocks.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oldest Value",
   "type": "stat",
   "description": "Oldest timestamp value stored in the database.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(prometheus_tsdb_lowest_timestamp_seconds)-prometheus_tsdb_lowest_timestamp_seconds{instance=\"$instance\"}",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "description": "Total user and system CPU time of Prometheus process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "description": "Resident memory size of Prometheus process",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Targets per Job",
   "type": "stat",
   "description": "Current number of targets in this scrape pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_target_scrape_pool_targets{instance=\"$instance\"}",
     "legendFormat": "{{ scrape_job }}"
    }
   ]
  },
  {
   "title": "Unknown Connection Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "increase(net_conntrack_dialer_conn_failed_total{instance=\"$instance\",reason=\"unknown\"}[$__rate_interval])",
     "legendFormat": "{{dialer_name}}"
    }
   ]
  },
  {
   "title": "Query Duration (p90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{instance=\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Query Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "TSDB Clean Start",
   "type": "stat",
   "description": "Lockfile state from previous execution: CLEAN (no lockfile), REPLACED (lockfile replaced), DISABLED (lockfile disabled).",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_clean_start{instance=\"$instance\"}",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Data Blocks",
   "type": "stat",
   "description": "Number of currently loaded data blocks",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Checkpoints Created",
   "type": "stat",
   "description": "Total number of checkpoint creations attempted.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_checkpoint_creations_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Checkpoints Deleted",
   "type": "stat",
   "description": "Total number of checkpoint deletions attempted.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_checkpoint_deletions_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Truncations",
   "type": "stat",
   "description": "Total number of write log truncations attempted.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_wal_truncations_total{instance=\"$instance\"}[$__range])",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Symbol Table RAM",
   "type": "stat",
   "description": "Size of symbol table in memory for loaded blocks",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_symbol_table_size_bytes{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metadata Cache",
   "type": "stat",
   "description": "Metric metadata in the cache for target scraping.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_target_metadata_cache_bytes{instance=\"$instance\"})",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Replay Time",
   "type": "stat",
   "description": "Time taken to replay the data on disk.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_data_replay_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "Page Completion/Flush Rate",
   "type": "timeseries",
   "description": "Page completion/flush rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_completed_pages_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "completed"
    },
    {
     "expr": "rate(prometheus_tsdb_wal_page_flushes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "flushes"
    }
   ]
  },
  {
   "title": "WAL fsync Duration",
   "type": "timeseries",
   "description": "Duration (p99) of write log fsync.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_fsync_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  }
 ]
}