{
 "title": "Switch",
 "tags": [ "Omada" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "rate_interval", "query": "6m" },
   { "name": "device_type", "query": "Switch" },
   {
    "name": "port_ID",
    "query": {
     "query": "label_values(port_info{deviceType=\"$device_type\"},portID)"
    }
   },
   {
    "name": "max_port_speed",
    "query": {
     "query": "query_result(scalar(max(max_over_time(port_speed{deviceType=\"$device_type\"}[$__range]))))"
    }
   },
   {
    "name": "device_name",
    "label": "Controler Name",
    "query": {
     "query": "label_values(device_last_seen{job=\"Omada\"},device_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transferred",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval])) +\n  abs(deriv(port_rx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval]))\n) * $__range",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval])) +\n  abs(deriv(port_rx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval]))\n) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    count(port_speed{deviceType=\"$device_type\", device_name=\"$device_name\"} > 0) /\n    count(port_speed{deviceType=\"$device_type\", device_name=\"$device_name\"})\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage{deviceType=\"$device_type\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage{deviceType=\"$device_type\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port $port_ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "repeat": "port_ID",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "port_speed{deviceType=\"$device_type\", device_name=\"$device_name\", portID=\"$port_ID\"}\n  * on(macAddress, portID) group_left(portName, portMode)\nport_info{deviceType=\"$device_type\", device_name=\"$device_name\", portID=\"$port_ID\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port $port_ID - data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "repeat": "port_ID",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\", portID=\"$port_ID\"}[$rate_interval])) +\n  abs(deriv(port_rx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\", portID=\"$port_ID\"}[$rate_interval]))\n) * $__range",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Switch port TX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval]))\n) * 8\n* on (macAddress, portID) group_left(portName, portMode)\nmax(port_info{deviceType=\"$device_type\", device_name=\"$device_name\"} == 1) by (macAddress, portID, portName, portMode)",
     "legendFormat": "{{portID}} - {{portName}}"
    }
   ]
  },
  {
   "title": "Switch port RX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(\n  abs(deriv(port_rx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval]))\n) * 8\n* on (macAddress, portID) group_left(portName, portMode)\nmax(port_info{deviceType=\"$device_type\", device_name=\"$device_name\"} == 1) by (macAddress, portID, portName, portMode)",
     "legendFormat": "{{portID}} - {{portName}}"
    }
   ]
  },
  {
   "title": "Resource consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "cpu_usage{deviceType=\"$device_type\", device_name=\"$device_name\"}\n* on (macAddress) group_left(deviceName)\nmax(device_info{deviceType=\"$device_type\", device_name=\"$device_name\"} == 1) by (macAddress, deviceName)  ",
     "legendFormat": "{{deviceName}} (CPU)"
    },
    {
     "expr": "memory_usage{deviceType=\"$device_type\"}\n* on (macAddress) group_left(deviceName)\nmax(device_info{deviceType=\"$device_type\"} == 1) by (macAddress, deviceName)  ",
     "legendFormat": "{{deviceName}} (RAM)"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "device_info{deviceType=\"$device_type\", device_name=\"$device_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Switch Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  abs(deriv(port_tx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval])) +\n  abs(deriv(port_rx_bytes_total{deviceType=\"$device_type\", device_name=\"$device_name\"}[$rate_interval]))\n) * 8",
     "legendFormat": "Switch Throughput"
    }
   ]
  }
 ]
}