{
 "title": "Synology NAS",
 "tags": [ "Synology" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheusJobName", "query": "Synology" },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "query_result(ssCpuUser{job=~'$prometheusJobName'})"
    }
   },
   {
    "name": "storageDevice",
    "label": "Storage Device",
    "query": {
     "query": "label_values(storageIODevice{job=\"$prometheusJobName\", instance=\"$device\"},storageIODevice)"
    }
   },
   {
    "name": "joinRaidNameToSpacePool",
    "query": "on(spaceIODevice) group_left(raidName)(     label_replace(spaceIOIndex == 1, \"raidName\", \"Volume 1\", \"__name__\", \".*\") or     label_replace(spaceIOIndex == 2, \"raidName\", \"Volume 2\", \"__name__\", \".*\") or     label_replace(spaceIOIndex == 3, \"raidName\", \"Volume 3\", \"__name__\", \".*\") or     label_replace(spaceIOIndex == 4, \"raidName\", \"Volume 4\", \"__name__\", \".*\") or     label_replace(spaceIOIndex == 5, \"raidName\", \"Volume 5\", \"__name__\", \".*\") or     label_replace(spaceIOIndex == 6, \"raidName\", \"Volume 6\", \"__name__\", \".*\") or     label_replace(spaceIOIndex == 7, \"raidName\", \"Volume 7\", \"__name__\", \".*\") or     label_replace(spaceIOIndex == 8, \"raidName\", \"Volume 8\", \"__name__\", \".*\") or     label_replace(spaceIOIndex == 9, \"raidName\", \"Volume 9\", \"__name__\", \".*\") or     label_replace(spaceIOIndex == 10, \"raidName\", \"Volume 10\", \"__name__\", \".*\") )"
   }
  ]
 },
 "panels": [
  {
   "title": "System Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(raidTotalSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"}) - sum(raidFreeSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"}))/sum(raidTotalSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(raidTotalSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diskStatus{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "{{diskID}}"
    }
   ]
  },
  {
   "title": "RAID Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidStatus{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"}",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "modelName{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "version{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "serialNumber{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memTotalReal{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "systemStatus{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerStatus{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "upgradeAvailable{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpuFanStatus{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sysUpTime{job=~'$prometheusJobName',instance=~'$device'}/100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "diskStatus{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "diskModel{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "diskTemperature{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "diskType{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Space",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(raidTotalSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"} - raidFreeSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"})/raidTotalSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"}",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "System"
    },
    {
     "expr": "diskTemperature{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "{{diskID}}"
    }
   ]
  },
  { "title": "Computing Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Utilization ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ssCpuSystem{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "System"
    },
    {
     "expr": "ssCpuUser{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Memory Utilization ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(memTotalReal{job=~'$prometheusJobName',instance=~'$device'} - (memAvailReal{job=~'$prometheusJobName',instance=~'$device'} + memCached{job=~'$prometheusJobName',instance=~'$device'} + memBuffer{job=~'$prometheusJobName',instance=~'$device'})) / memTotalReal{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "laLoadInt{job=~'$prometheusJobName',instance=~'$device'}/100",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalReal{job=~'$prometheusJobName',instance=~'$device'} - (memShared{job=~'$prometheusJobName',instance=~'$device'} + memCached{job=~'$prometheusJobName',instance=~'$device'} + memBuffer{job=~'$prometheusJobName',instance=~'$device'} + memAvailReal{job=~'$prometheusJobName',instance=~'$device'})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "memBuffer{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "memCached{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "memShared{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "Shared"
    },
    {
     "expr": "memAvailReal{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface",
     "type": "table",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 136 },
     "targets": [
      {
       "expr": "ifPhysAddress{job=~'$prometheusJobName',instance=~'$device', ifName=~\"eth[0-9]+$\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "ifOperStatus{job=~'$prometheusJobName',instance=~'$device', ifName=~\"eth[0-9]+$\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "ifSpeed{job=~'$prometheusJobName',instance=~'$device', ifName=~\"eth[0-9]+$\"}",
       "legendFormat": "__auto"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Network Load",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 15, "x": 9, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "((rate(ifHCInOctets{job=~'$prometheusJobName',instance=~'$device', ifName=~\"eth[0-9]+$\"}[$__rate_interval])*8) + (rate(ifHCOutOctets{job=~'$prometheusJobName',instance=~'$device', ifName=~\"eth[0-9]+$\"}[$__rate_interval])*8))/ifSpeed{job=~'$prometheusJobName',instance=~'$device', ifName=~\"eth[0-9]+$\"}",
       "legendFormat": "{{ifName}}"
      }
     ]
    },
    {
     "title": "Traffic In",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(ifHCInOctets{job=~'$prometheusJobName',instance=~'$device', ifName=~\"eth[0-9]+$\"}[$__rate_interval])*8",
       "legendFormat": "{{ifName}}"
      }
     ]
    },
    {
     "title": "Traffic Out",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(ifHCOutOctets{job=~'$prometheusJobName',instance=~'$device', ifName=~\"eth[0-9]+$\"}[$__rate_interval])*8",
       "legendFormat": "{{ifName}}"
      }
     ]
    }
   ]
  },
  { "title": "Storage Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Used Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(raidTotalSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"} - raidFreeSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"})/raidTotalSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"}",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "raidFreeSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "raidTotalSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"} -raidFreeSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "raidTotalSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(raidTotalSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"} -raidFreeSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"}) / raidTotalSize{job=~'$prometheusJobName',instance=~'$device', raidName=~\"Volume [0-9]+$\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(spaceIONReadX{job=~'$prometheusJobName',instance=~'$device'}[$__rate_interval]) + rate(spaceIONWrittenX{job=~'$prometheusJobName',instance=~'$device'}[$__rate_interval]))\n  * $joinRaidNameToSpacePool",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(spaceIOReads{job=~'$prometheusJobName',instance=~'$device'}[$__rate_interval])\n+ rate(spaceIOWrites{job=~'$prometheusJobName',instance=~'$device'}[$__rate_interval]))\n  * $joinRaidNameToSpacePool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Space Load",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "spaceIOLA\n* $joinRaidNameToSpacePool",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  {
   "title": "Space Load 1",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 54 },
   "targets": [
    {
     "expr": "spaceIOLA1\n* $joinRaidNameToSpacePool",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  {
   "title": "Space Load 5",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "spaceIOLA5\n* $joinRaidNameToSpacePool",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  {
   "title": "Space Load 15",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 54 },
   "targets": [
    {
     "expr": "spaceIOLA15\n* $joinRaidNameToSpacePool",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  {
   "title": "I/O Reads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "rate(spaceIOReads{job=~'$prometheusJobName',instance=~'$device'}[$__rate_interval])\n  * $joinRaidNameToSpacePool",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  {
   "title": "I/O Writes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "rate(spaceIOWrites{job=~'$prometheusJobName',instance=~'$device'}[$__rate_interval])\n  * $joinRaidNameToSpacePool",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  {
   "title": "Read throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(spaceIONReadX{job=~'$prometheusJobName',instance=~'$device'}[$__rate_interval])\n  * $joinRaidNameToSpacePool",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  {
   "title": "Write throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(spaceIONWrittenX{job=~'$prometheusJobName',instance=~'$device'}[$__rate_interval])\n  * $joinRaidNameToSpacePool",
     "legendFormat": "{{raidName}}"
    }
   ]
  },
  { "title": "Storage Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "S.M.A.R.T",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "label_replace(\n  diskSMARTInfoDevName{job=~\"$prometheusJobName\", instance=~\"$device\"},\n  \"storageIODevice\", \"$1\", \"diskSMARTInfoDevName\", \".*/([^/]+)$\"\n)",
     "legendFormat": "SMARTInfo"
    },
    {
     "expr": "diskSMARTAttrName{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "AttrName"
    },
    {
     "expr": "diskSMARTAttrCurrent{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "AttrCurrent"
    },
    {
     "expr": "diskSMARTAttrThreshold{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "AttrThreshold"
    },
    {
     "expr": "diskSMARTAttrWorst{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "AttrWorst"
    },
    {
     "expr": "diskSMARTAttrStatus{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "AttrStatus"
    },
    {
     "expr": "diskSMARTAttrRaw{job=~'$prometheusJobName',instance=~'$device'}",
     "legendFormat": "AttrRaw"
    }
   ]
  },
  {
   "title": "Failing SMART Checks",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  label_replace(\n    diskSMARTAttrStatus{diskSMARTAttrStatus!=\"OK\"}\n      * on(instance, job, diskSMARTInfoIndex) group_left(diskSMARTInfoDevName)\n      diskSMARTInfoDevName,\n    \"storageIODevice\", \"$1\", \"diskSMARTInfoDevName\", \".*/([^/]+)$\"\n  )\n) by (storageIODevice)\nor\ncount(\n  label_replace(\n    diskSMARTAttrStatus\n      * on(instance, job, diskSMARTInfoIndex) group_left(diskSMARTInfoDevName)\n      diskSMARTInfoDevName,\n    \"storageIODevice\", \"$1\", \"diskSMARTInfoDevName\", \".*/([^/]+)$\"\n  )\n) by (storageIODevice) * 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Reads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "rate(storageIOReads{job=~'$prometheusJobName',instance=~'$device', storageIODevice=~'$storageDevice'}[$__rate_interval])",
     "legendFormat": "{{storageIODevice}}"
    }
   ]
  },
  {
   "title": "I/O Writes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "rate(storageIOWrites{job=~'$prometheusJobName',instance=~'$device', storageIODevice=~'$storageDevice'}[$__rate_interval])",
     "legendFormat": "{{storageIODevice}}"
    }
   ]
  },
  {
   "title": "Read throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(storageIONReadX{job=~'$prometheusJobName',instance=~'$device', storageIODevice=~'$storageDevice'}[$__rate_interval])",
     "legendFormat": "{{storageIODevice}}"
    }
   ]
  },
  {
   "title": "Write throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(storageIONWrittenX{job=~'$prometheusJobName',instance=~'$device', storageIODevice=~'$storageDevice'}[$__rate_interval])",
     "legendFormat": "{{storageIODevice}}"
    }
   ]
  }
 ]
}