{
 "title": "UPS",
 "tags": [
  "GreenCell",
  "Synology"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobName", "label": "JobName", "query": "Synology" }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upsInfoLoadValue", "legendFormat": "{{__name__}}-{{job}}" }
   ]
  },
  {
   "title": "Input",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsInputVoltageValue{job=\"$jobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsOutputVoltageValue{job=\"$jobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsBatteryVoltageValue{job=\"$jobName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "upsInfoLoadValue{job=\"$jobName\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "upsBatteryVoltageValue{job=\"$jobName\"}",
     "legendFormat": "batteryVoltage"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "upsInputVoltageValue{job=\"$jobName\"}",
     "legendFormat": "Input"
    },
    {
     "expr": "upsOutputVoltageValue{job=\"$jobName\"}",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "upsInputFrequencyValue{job=\"$jobName\"}",
     "legendFormat": "Input"
    }
   ]
  }
 ]
}