{
 "title": "Router",
 "tags": [ "Omada" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "increase_interval", "query": "1m" }
  ]
 },
 "panels": [
  {
   "title": "WAN LoadBalancing Active Port",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_port_info{mode=\"WAN\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_port_info{port=\"1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_port_info{port=\"2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_port_info{port=\"3\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_port_info{port=\"4\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_port_info{port=\"5\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_port_info{port=\"6\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 7",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_port_info{port=\"7\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 8",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_port_info{port=\"8\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resource consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "cpu_usage{deviceType=\"Router\"}",
     "legendFormat": "{{name}} ({{__name__}})"
    },
    {
     "expr": "memory_usage{deviceType=\"Router\"}",
     "legendFormat": "{{name}} ({{__name__}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "router_temperature", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Rate port 1",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(router_port_tx_sum{port=\"1\"}[$increase_interval]) + increase(router_port_rx_sum{port=\"1\"}[$increase_interval]))\n  * on (port) group_left()\n  (router_port_info{port=\"1\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(router_port_tx_sum{port=\"2\"}[$increase_interval]) + increase(router_port_rx_sum{port=\"2\"}[$increase_interval]))\n  * on (port) group_left()\n  (router_port_info{port=\"2\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 3",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(router_port_tx_sum{port=\"3\"}[$increase_interval]) + increase(router_port_rx_sum{port=\"3\"}[$increase_interval]))\n  * on (port) group_left()\n  (router_port_info{port=\"3\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 4",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(router_port_tx_sum{port=\"4\"}[$increase_interval]) + increase(router_port_rx_sum{port=\"4\"}[$increase_interval]))\n  * on (port) group_left()\n  (router_port_info{port=\"4\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 5",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(router_port_tx_sum{port=\"5\"}[$increase_interval]) + increase(router_port_rx_sum{port=\"5\"}[$increase_interval]))\n  * on (port) group_left()\n  (router_port_info{port=\"5\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 6",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(router_port_tx_sum{port=\"6\"}[$increase_interval]) + increase(router_port_rx_sum{port=\"6\"}[$increase_interval]))\n  * on (port) group_left()\n  (router_port_info{port=\"6\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 7",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(router_port_tx_sum{port=\"7\"}[$increase_interval]) + increase(router_port_rx_sum{port=\"7\"}[$increase_interval]))\n  * on (port) group_left()\n  (router_port_info{port=\"7\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 8",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (increase(router_port_tx_sum{port=\"8\"}[$increase_interval]) + increase(router_port_rx_sum{port=\"8\"}[$increase_interval]))\n  * on (port) group_left()\n  (router_port_info{port=\"8\", linkSpeed!=\"Down\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "router_port_loss\n  * on(mac, port) \n  group_left(mode, portDesc) \n  router_port_info{mode=\"WAN\"}",
     "legendFormat": "{{portDesc}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "router_port_latency\n  * on(mac, port) \n  group_left(mode, portDesc) \n  router_port_info{mode=\"WAN\"}",
     "legendFormat": "{{portDesc}}"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "device_info{deviceType=\"Router\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAN IPv4 Config",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 30 },
   "targets": [
    { "expr": "router_port_ipv4_config_info", "legendFormat": "__auto" }
   ]
  }
 ]
}