{
 "title": "Switch",
 "tags": [ "Omada" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Port 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"3\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 5",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"5\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 7",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"7\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 9",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 11",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"11\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 13",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"13\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 15",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"15\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 17",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"17\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "device_info{deviceType=\"Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Port 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"4\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"6\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 8",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"8\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 10",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"10\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 12",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"12\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 14",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"14\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 16",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"16\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port 18",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_info{port=\"18\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rate port 1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"1\"} + switch_port_tx_rate{port=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"3\"} + switch_port_tx_rate{port=\"3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"5\"} + switch_port_tx_rate{port=\"5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 7",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"7\"} + switch_port_tx_rate{port=\"7\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 9",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"9\"} + switch_port_tx_rate{port=\"9\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 11",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"11\"} + switch_port_tx_rate{port=\"11\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 13",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"13\"} + switch_port_tx_rate{port=\"13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 15",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"15\"} + switch_port_tx_rate{port=\"15\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"2\"} + switch_port_tx_rate{port=\"2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"4\"} + switch_port_tx_rate{port=\"4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 6",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"6\"} + switch_port_tx_rate{port=\"6\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 8",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"8\"} + switch_port_tx_rate{port=\"8\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 10",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"10\"} + switch_port_tx_rate{port=\"10\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 12",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"12\"} + switch_port_tx_rate{port=\"12\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 14",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"14\"} + switch_port_tx_rate{port=\"14\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 16",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"16\"} + switch_port_tx_rate{port=\"16\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 17 SFP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"17\"} + switch_port_tx_rate{port=\"17\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate port 18 SFP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_port_rx_rate{port=\"18\"} + switch_port_tx_rate{port=\"18\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "cpu_usage{deviceType=\"Switch\"}",
     "legendFormat": "{{name}} ({{__name__}})"
    },
    {
     "expr": "memory_usage{deviceType=\"Switch\"}",
     "legendFormat": "{{name}} ({{__name__}})"
    }
   ]
  }
 ]
}